### ISSUE TITLE
Crash while athena has a map loaded

### ISSUE THREAD

**Issue by SekiAlpha** [WolfCorps/TacControl#10]
If Athena has had a previous map loaded, and you start up Arma 3 with TacControl Arma 3 crashes before loading into the main menu.

Here are the crash reports:
[Crash.zip](https://github.com/WolfCorps/TacControl/files/6185411/Crash.zip)

I can't personally replicate the issue on my machine but I'm hoping that the crash files would help figure out why this CTD is happening.

**Comment by dedmen** [comment]
It crashed inside taccontrol definitely.
Sorry I didn't keep the debug files from before the last update (today).
Can you get a new mdmp with the latest workshop version that was pushed today?
I only need the mdmp nothing else

**Comment by SekiAlpha** [comment]
Sure thing I'll contact the guy who has the crash and I'll do another test today.

**Comment by SekiAlpha** [comment]
He has yet to respond to me :(

**Comment by Sm1ttyman** [comment]
[Arma3_x64_2021-03-25_20-44-43.zip](https://github.com/WolfCorps/TacControl/files/6208827/Arma3_x64_2021-03-25_20-44-43.zip)
Here's the mdmp. I'm the problem-child lol

**Comment by dedmen** [comment]
It crashed while trying to open the arma side server.
On TCP port 8082.
That shouldn't be related to Athena? does Athena use port 8082? :u

**Comment by SekiAlpha** [comment]
According to the steam workshop page for athena "Athena Relay listens on
TCP Port 28800"

**Comment by dedmen** [comment]
With next update it should not crash anymore, and instead show the error message of whats wrong.
Feel free to post the error message here and reopen if it doesn't just say "port is already in use"
