### ISSUE TITLE
Switch mouse button usage

### ISSUE THREAD

**Issue by otting** [WolfCorps/TacControl#17]
switch mouse button usage, it is the opposite to arma standard, which confuses a lot.

**Comment by SekiAlpha** [comment]
It's been updated to use the Arma 3 standard. Ctrl + click to draw for example.

**Comment by dedmen** [comment]
Yes its same as Arma. And has been for a couple days :eyes: 
Better stay on latest steam workshop version. There will be frequent updates during alpha
